# Generated by Django 5.1.6 on 2025-04-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_chatsession_chatmessage_delete_consultation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
